### ISSUE TITLE
Any other way to create an unique map 

### ISSUE THREAD

**Issue by oykuyener** [lgsvl/PythonAPI#49] opened 2021-08-02 10:20 UTC
Hello, I wanted to customize my map but because of it is API Only,  I couldn't do anything with it, no changes, no customization. Are there any ways to edit my test-case scenarios in API Only map ?

**Comment by heeen** [comment] 2021-08-02 11:59
duplicate of https://github.com/lgsvl/simulator/issues/1651

**Closed** 2021-08-02 13:44 UTC
