### ISSUE TITLE
execution of NPCs in the LG simulator is not deterministic

### ISSUE THREAD

**Issue by yl2280** [lgsvl/PythonAPI#14] opened 2019-11-14 16:54 UTC
I found the execution of NPCs in the LG simulator is not
deterministic. Meaning if I repeat the same scenarios that I programmed
via PythonAPI (i.e., follow-lane, making lane change of NPCs), every
time I see a slightly different behaviors of NPCs (i.e., different
trajectories etc). Why? Can someone explain it for me and point me where
to look at in the code? (I assume there are stochastic process in the
simulator).

**Comment by martins-mozeiko** [comment] 2019-11-14 18:54
Closing as duplicate of https://github.com/lgsvl/simulator/issues/496

**Closed by martins-mozeiko** 2019-11-14 18:54 UTC
